### ISSUE TITLE
SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by modernNeo** [passbolt/passbolt_docker#112] opened 2018-10-12 06:01 UTC
### How to provide a good issue report:
- Provide all the information you can collect about your problem  
  
I was going through the instructions outline here on my ubuntu: https://help.passbolt.com/hosting/install/ce/docker

I am a bit of a novice to databases and so forth, I expect I am making a dumb mistake but not sure what it is and would appreciate a poke in the right direction.

I have included the commands and the output at the bottom of this comment
- Provide log outputs from (some examples follow):
  - /var/www/passbolt/tmp/logs/error.log -> i tried to get this but there was no `logs` folder in the `tmp` folder
  - /var/log/nginx/error.log -> no entries
  - curl -vvvLk http://passboltdomain
  - Any other sources you might think will help to solve the problem

### What you did :memo:
Explain what you did, steps to reproduce your issue, here.

### What happened :collision: :clipboard:
Provide information such as log outputs in this section showing what is
happening.

### What you expected to happen
Explain what is the expected behaviour.
[error_output.txt](https://github.com/passbolt/passbolt_docker/files/2471772/error_output.txt)

**Comment by dlen** [comment] 2018-10-12 07:07
Hi @modernNeo 

Sorry to hear that you are having problems setting up passbolt. Looks like your host lacks some of the requirements (rng-tools) as gnupg seems to be stuck in the key generation process not allowing passbolt to start. Also use mariadb instead mysql as per #103

**Comment by modernNeo** [comment] 2018-10-12 09:19
@dlen thanks for the pointers, that has helped alot. one final issue remains though....
I do the following commands
`root@password-manager:~# docker run --name mariadb --net passbolt_network -e MARIADB_ROOT_PASSWORD=8AaknQqbW9ohB -e MARIADB_DATABASE=CSSS_PASSWORDS -e MARIADB_USER=CSSS -e MARIADB_PASSWORD=csss_passbolt mariadb
error: database is uninitialized and password option is not specified
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD`

I am wondering why it wants me to specify `MYSQL_ROOT_PASSWORD` rather than `MARIADB_ROOT_PASSWORD`?

furthermore, if I do use `MYSQL_ROOT_PASSWORD`, I get an output that complains about "Access denied for user "CSSS"....but I am not sure why since the password I pass in is the same as the password I used when starting the mariadb container.

[container_setup.txt](https://github.com/passbolt/passbolt_docker/files/2472422/container_setup.txt)

**Comment by dlen** [comment] 2018-10-12 09:37
Hi @modernNeo, 

Glad to see the recommendations worked!
Your issue is because when launching mariadb container you are using incorrect environment variables such as `MARIADB_DATABASE`, `MARIADB_USER` and `MARIADB_PASSWORD` thus your database and user are not created in mariadb.

I'm closing this issue as your case is an installation problem and not a bug of passbolt_api or passbolt_docker. If you want to continue this conversation please use the [community forum](https://community.passbolt.com).

Cheers

**Closed by dlen** 2018-10-12 09:37 UTC
