### ISSUE TITLE
Docker container healthcheck shows error for base url even though env var is set to https

### ISSUE THREAD

**Issue by s4ke** [passbolt/passbolt_docker#152] opened 2021-02-25 11:08 UTC
The env variable has been set to `APP_FULL_BASE_URL=https://<base-url-without-slash-at-the-end>`

We have these mounts:

      - "/data/ansible/passbolt/data/gpg:/etc/passbolt/gpg"
      - "/data/ansible/passbolt/data/images:/usr/share/php/passbolt/webroot/img/public"
      - "/data/ansible/certs/{{ passbolt_cert_dir }}:/certs"
      - "/data/ansible/passbolt/mariadb/mariadb.cnf:/etc/mysql/mariadb.conf.d/mariadb.cnf"

![grafik](https://user-images.githubusercontent.com/719760/109144853-0471cf80-7762-11eb-9be1-423fad75961b.png)

**Comment by dlen** [comment] 2021-02-25 11:09
Hi @s4ke ,

Thanks for your report I think this is a duplicate of: https://github.com/passbolt/passbolt_api/issues/378

**Comment by s4ke** [comment] 2021-02-25 11:11
Ah, yes. Sorry, I wrongly assumed this was an issue with the env vars. This can be closed then.

**Closed** 2021-02-25 11:54 UTC
