### ISSUE TITLE
SMTP credentials update -- test email works but actual app emails not sent

### ISSUE THREAD

**Issue by nubela** [passbolt/passbolt_docker#138] opened 2020-01-21 01:51 UTC
Hi,

I am working on an existing container of passbolt_docker, and I restarted it with fresh SMTP credentials and sending test emails work.

However, emails from the actual application does not work. Logs come up empty. How can I fix this?

**Comment by dlen** [comment] 2020-01-22 13:32
Hi @nubela!

You could take a look on the database there is a table for the email_queue you can check if the queue contains your pending emails and in which state they are. Also check on the UI the notifications tab just in case they are disabled. 
You can also send emails using:

`su -c "bin/cake passbolt EmailQueueSender" -s /bin/bash www-data`

**Comment by dlen** [comment] 2020-04-20 17:02
Feel free to reopen with more information

**Comment by Frederik-Baetens** [comment] 2020-07-05 22:05
`su -c "bin/cake passbolt EmailQueueSender" -s /bin/bash www-data`

Doesn't work on 2.13.0-debian. I get :

```
root@infra-passbolt-6f55c5db8d-gwg7n:/var/www/passbolt# su -c "bin/cake passbolt EmailQueueSender" -s /bin/bash www-data
No subcommand provided. Choose one of the available subcommands.

Unable to find the `passbolt email_queue_sender` subcommand. See `bin/cake passbolt --help`.
```
Same issue here with sending the mails, the test mails work, but other's don't.

Only thing in the logs is:

```
2020-07-05 21:41:06 Debug: command 'preview' in plugin 'EmailQueue' was not aliased, conflicts with 'Passbolt/EmailDigest'
2020-07-05 21:41:06 Debug: command 'sender' in plugin 'EmailQueue' was not aliased, conflicts with 'Passbolt/EmailDigest'
```

**Comment by Frederik-Baetens** [comment] 2020-07-05 22:13
./bin/cake EmailQueue.preview

Gives:

```
Email :
Notice Error: Undefined index: fullBaseUrl in [/var/www/passbolt/src/Template/Email/html/AN/user_register_self.ctp, line 19]

2020-07-05 22:08:04 Notice: Notice (8): Undefined index: fullBaseUrl in [/var/www/passbolt/src/Template/Email/html/AN/user_register_self.ctp, line 19]


Exception: Argument 1 passed to App\View\Helper\AvatarHelper::getAvatarUrl() must be an instance of App\Model\Entity\Avatar, null given, called in /var/www/passbolt/src/Template/Email/html/AN/user_register_self.ctp on line 25 in [/var/www/passbolt/src/View/Helper/AvatarHelper.php, line 16]
```
./bin/cake EmailQueue.sender gives no output and still doesn't send my mails

I also checked the emailqueue in the db:
```
MariaDB [passbolt]> select id, email, send_tries, sent, error from email_queue order by id desc limit 10;
+-----+---------------------------+------------+------+---------------+
| id  | email                     | send_tries | sent | error         |
+-----+---------------------------+------------+------+---------------+
| 991 | xxx@xxx.xxx |          0 |    1 | NULL          |
| 990 | xxx@xxx.xxx |          0 |    1 | NULL          |
| 989 | xxx@xxx.xxx |          0 |    1 | NULL          |
```
(email adresses were anonimized by me) The from_email in that table is also null, despite me listing one in the config.

**Comment by dlen** [comment] 2020-07-06 07:05
Hi @Frederik-Baetens ,

Sorry my previous post had a mistake:

`su -c "source /etc/environment ; /var/www/passbolt/bin/cake EmailQueue.sender" -s /bin/bash www-data`

Could you confirm you have the same issues?

**Comment by Frederik-Baetens** [comment] 2020-07-06 14:56
That gives no output, and no mails seem to get sent.

**Comment by stripthis** [comment] 2020-07-06 15:08
@Frederik-Baetens  if there is no email it means that no email in the queue needs to be sent. According to the result you listed, the emails where already sent. Maybe there is an issue with the delivery after that?

**Comment by Frederik-Baetens** [comment] 2020-07-06 18:22
I tried the passbolt mail delivery test and that works fine.

**Comment by Frederik-Baetens** [comment] 2020-07-06 18:24
Is it normal for the sent tried to be 0 but the mail is marked as sent?

**Comment by Frederik-Baetens** [comment] 2020-07-08 08:34
Any other suggestions? I can edit the source code files and put some print statements in suggested positions if you want.

**Comment by stripthis** [comment] 2020-07-08 08:42
> Is it normal for the send tries to be 0 but the mail is marked as sent?
Yes, I believe it is normal if the email is sent on first try. E.g sent_tries is incremented only if there is an error (from the application point of view)

**Comment by Frederik-Baetens** [comment] 2020-07-09 11:41
Hmm, to be honest, this might have been caused by mail delivery issues on my end due to a bad configuration. I just enabled dkim, and dmarc, so i think these mails might have been getting marked as spam by the email provider in such a way that they didn't even arrive as junk email.

Sorry for bothering you with this.

**Comment by dlen** [comment] 2020-07-09 11:45
Thanks for the update @Frederik-Baetens I'm closing the issue!

**Closed by dlen** 2020-07-09 11:45 UTC
Labels: installation issue
